name: Backup Blocklist

on: push
#  schedule:
#    - cron: '0 */6 * * *'

jobs:
  backup_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Files
      run: |
        curl -o backup/ads.txt https://blocklist.oli11gh.top/f/ads.txt
        curl -o backup/ads-2.txt https://blocklist.oli11gh.top/f/ads-2.txt
        curl -o backup/ads-3.txt https://blocklist.oli11gh.top/f/ad-s3.txt
        curl -o backup/gen.txt https://blocklist.oli11gh.top/f/gen.txt
        curl -o backup/gen-2.txt https://blocklist.oli11gh.top/f/gen-2.txt
        curl -o backup/gen-3.txt https://blocklist.oli11gh.top/f/gen-3.txt
        curl -o backup/gen-4.txt https://blocklist.oli11gh.top/f/gen-4.txt
        curl -o backup/gen-5.txt https://blocklist.oli11gh.top/f/gen-5.txt
        curl -o backup/other-junk.txt https://blocklist.oli11gh.top/f/other-junk.txt
        curl -o backup/porn.txt https://blocklist.oli11gh.top/f/porn.txt
        curl -o backup/porn-2.txt https://blocklist.oli11gh.top/f/porn-2.txt
        curl -o backup/porn-3.txt https://blocklist.oli11gh.top/f/porn-3.txt

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config --local user.email ${{ secrets.EMAIL }}
        git config --local user.name "Backuper"
        git add .
        git commit -m "Create blocklist backup"
        git push
