name: Generate Blocklist Hosts

on: push
#on:
#  schedule:
#    - cron: '0 */2 * * *'

jobs:
  backup_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '18'

#    - name: Install npm dependencies
#      run: npm install fs axios path

    - name: Update workflow
      run: git pull origin main
      
    - name: Run generator
      run: node index.js

    - name: Upload Files
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config --local user.email ${{ secrets.EMAIL }}
        git config --local user.name "Security Guy"
        git add hosts
        git commit -m "Generate hosts"
        git push origin main
